apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x74c9a3qh-python 
  janus-idp.io/tekton: x74c9a3qh-python
  backstage.io/kubernetes-id: x74c9a3qh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x74c9a3qh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  