apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x74c9a3qh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x74c9a3qh-python 
  name: x74c9a3qh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x74c9a3qh-python 
